### ISSUE TITLE
[Accessibility] Input component "clear" button is not keyboard accessible

### ISSUE THREAD

**Issue by joheredi** [microsoft/fluent-ui-react#1024]
### Steps
```jsx
<Input clearable placeholder="Search..." />
```

### Expected Result
Be able to clear the input content with the keyboard

### Actual Result
"Clear" button is not accessible with the keyboard

### Version
0.23.0

**Comment by silviuaavram** [comment]
We probably need to discuss this a bit further, I don't think it should.

The example above looks almost identical to the case of basic HTML `<input type="search">`

There will be an X icon generated when the input has text, but it's only clickable. To clear text by keyboard, you press Escape.

In our `clearable` version, we don't clear text on escape. Maybe we should make these changes instead, so it can behave as a search type. Semantically better would be `search` instead of `clearable`.
