### ISSUE TITLE
Accessibility: Focus border is not rendered correctly on the grid component

### ISSUE THREAD

**Issue by johannao76** [microsoft/fluent-ui-react#1035]
## Bug Report
Focus border is not rendered correctly on the grid component

### Steps
Use the provided link, tab to the first item in the grid, use arrows to navigate through the items.

### Expected Result
The focus box should be rendered properly

### Actual Result
The focus box around the items is not rendered properly, gets cut off in some spots

### Version
0.23.0

### Testcase
https://codesandbox.io/s/9y5qylv8o4

**Comment by dslane** [comment]
This is caused by adding an overflowY style of "auto" or "scroll". Here is a codesandbox with two identical grids, but one has an overflowY set and the other doesn't. You can see that the one without overflowY has correct focus borders, but the one with it has cut-off borders around the edges of the grid

https://codesandbox.io/s/6zp37k9kwn

**Comment by dslane** [comment]
This needs to be fixed by stardust, either by providing a different mechanism for scrolling or by building margins into the grid so that overflowY won't cut them off

**Comment by sophieH29** [comment]
@mnajdova @Bugaa92 @miroslavstastny @kuzhelov can you take a look on this?

**Comment by bmdalex** [comment]
@johannao76 @dslane @sophieH29 

thanks for reporting, will be fixed by #1195
