### ISSUE TITLE
Accordion not working when content is specified as an element

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#1272]
### Steps
Using element in the Accordion's panel's content breaks the behavior of the Accordion. Example:
```jsx
const panels = [
  {
    key: "p",
    title: "What is a point?",
    content: (
      <span>
        Use the haptic SDD circuit, then you can index the redundant pixel!
      </span>
    )
  },
  {
    key: "d",
    title: "What is a dimension of a point?",
    content: <span>We need to copy the primary USB firewall!</span>
  }
];

const AccordionExample = () => (
  <Accordion defaultActiveIndex={[0]} panels={panels} />
);
```

### Expected Result
The Accordion should still keep it's behavior (clicking title should open the panel and close the other), or at least note in the documentation that this is not supported.

### Actual Result
All panels are always open.

### Version
0.29.0

### Testcase
https://codesandbox.io/s/14mqj908n4

**Comment by levithomason** [comment]
When passing a shorthand element, the slot itself is replaced by your element.  This means the original panel content component which handles open/closed states has been replaced by a `span`.

Instead, you need to pass the span as a child to the `content` slot component:

**Working codepen: https://codesandbox.io/s/stardust-ui-example-x4pgt**

```diff
const panels = [
  {
    key: 'p',
    title: 'What is a point?',
-    content: <span>Use the haptic SDD circuit, then you can index the redundant pixel!</span>,
+    content: { children: <span>Use the haptic SDD circuit, then you can index the redundant pixel!</span> },
  },
  {
    key: 'd',
    title: 'What is a dimension of a point?',
-    content: <span>We need to copy the primary USB firewall!</span>,
+    content: { children: <span>We need to copy the primary USB firewall!</span> },
  },
]

const AccordionExample = () => <Accordion defaultActiveIndex={[0]} panels={panels} />

export default AccordionExample
```

### Future updates

We're working on changes to the shorthand API that will resolve this confusion, since it is pretty common.  For now, just use the children appropriately.
