### ISSUE TITLE
Allow disabling all animations (Animation and Loader components)

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#1273]
### Problem description

For testing purposes it should be possible to disable animations so that the screenshots would be stable

### Proposed solution
Add a prop to the provider (or theme) to disable animations.

**Comment by mnajdova** [comment]
Let me share here first all requirements that we have, with some possible solutions about how we want to approach this. First of all we have to have a way of disabling animations in part of the tree of the application. Next we should have a way to disable animations on component level. Last, some of the animations should never be stopped (like the loader for example). On other case, when we are testing these components, we want to stop the animation, in order to be able to consistently take a screenshot of the state of the component. Let me share some possible ways of how we can achieve this:

1. Disabling animations for some tree in the application
- we can add `disableAnimations` option in the theme, so when the users would like to disable the animation they can add Provider with a theme prop that will set this flag to true.
```
<Provider theme={{disableAnimations: true}}>
  {/* Application */}
</Provider>
```
- the other approach, would be to add the prop disableAnimations directly on the Provider, and then send it as a param of the theme that the consumer is sending down the tree, or add additional Context for this, that in the `renderComponent` will send this information to the component - we can decide then in the `Animation` component, or in the `renderComponent` whether we should add the animation (we already have the theme there, we can send this additional prop, or we can send this directly to the styles and use it there if we are defining some animation directly in the styles).

2. For disabling this on component level, even with the previous added option, we can wrap the component with the Provider for this purpose, or we can add general prop to all components (disableAnimation), that will make sure that it will be respected in the components - we already have the animation prop on all components, so this can be something related to that prop.

3. If there are some animations that should never be stopped, we can add prop on the animation definition that will mark this animations as `alwaysAnimatimate` or something similar. This will mean that, even if we disable animations on the component or Provider level, this animation will still play. This, however can produce problems in the tests, because when we are testing the Loader component, we really want it not to stop. Not sure how to make both of these scenarios work, without adding additional prop that will be used only in the test, and will stop animations no matter whether the animation should be stopped or not. I am open for ideas here.

@kuzhelov @miroslavstastny @layershifter @Bugaa92 please share you thoughts here.

**Comment by levithomason** [comment]
Conclusions and additional todos:

- [ ] Let's create a context package.  It should be extremely minimal, providing only the context channel.  This package will be consumable and shareable by all Stardust compliant frameworks.  This way, we enable component interop between frameworks.  Do not include any other features in the package.  It should attempt to _never_ have to be versioned, but be stable at the start.
- [ ] Restructure context to use the new context package.  Theme will become a key:
  ```jsx
  const context = {
    theme: {           // current theme
      siteVariables,
      componentVariables,
      componentStyles,
      fontFaces,
      staticStyles,
      icons,
      animations,
    },
    renderer: {},            // split from current theme
    rtl: {},                 // split from current theme
    disableAnimations: true, // new default value to skip animations
  }
  ```

- [ ] Update typings for theme types to not include `rtl` and `renderer`
- [ ] Review other libraries and patterns for dealing with disabling animations.
- [ ] Review other libraries and patterns for opting in/out of theme features.
