### ISSUE TITLE
Fela memory improvements

### ISSUE THREAD

**Issue by johannao76** [microsoft/fluent-ui-react#1311]
Ran a test in Teams after loading 400 messages
- The fela cache size is ~270KB
- Fela is also adding a lot of strings in memory due to bloated class names and reference to normalize.css:
![image](https://user-images.githubusercontent.com/11838969/57469055-92519300-723a-11e9-8b75-77ce32cdcc81.png)

![image](https://user-images.githubusercontent.com/11838969/57470001-b7df9c00-723c-11e9-83fe-de701a61cee2.png)

**Comment by layershifter** [comment]
### Normalize CSS

This string will included to memory only three times (in styles, Fela cache key & Fela cache value), after minification (#1476) it's less than 6 kb for all.

### Bloated classnames

These strings are values of `className` prop in React elements (that's why they are repeated):

![image](https://user-images.githubusercontent.com/14183168/59265947-c0196580-8c46-11e9-863d-0bf6b494a9d2.png)

So can you please suggest what exactly you want to get fixed there? If we will decide to go with monolithic classes (http://fela.js.org/docs/recipes/MonolithicClassNames.html) we will get even more memory consumption.

There is a problem with clearing references to props, but React team is working on improvements in that way: https://github.com/facebook/react/issues/14380 

### Real improvement

Currently when you have mixed mixed layout (LTR & RTL) we will use two renderers. Each renderer has own cache (key & value) and generates own classes (in RTL they are prefixed with `rtl_`). After #1459 we will use only single renderer.
