### ISSUE TITLE
Popups don't render properly when popup is larger than window size

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1391]
## Bug Report
When popups that are rendered as dialogs, i.e. rendered as a top level element underneath the document body rather than rendered underneath their trigger elements, are larger than the window size it can cause some weird rendering issues. 

### Steps
1. Create a popup whose content is rather tall.
2. Anchor its trigger to the bottom of the window
3. Shrink the window so that it's 

### Expected Result
I'd expect as much of the popup to be visible as possible and the overflow to be handled gracefully.

### Actual Result
The bottom dissappears underneath the window

### Version
0.31.0 

### Testcase
[Fork, update, and replace this pen to show the bug]:

Easiest to repro if you pop-out the sandbox.
https://codesandbox.io/s/stardustuiexample-qeku8

**Comment by bmdalex** [comment]
![Screen Recording 2019-06-03 at 14 21 15](https://user-images.githubusercontent.com/5442794/58801519-02212680-860b-11e9-8d2d-1f4129274683.gif)
@stuartlong - is this the correct repro?

> I'd expect as much of the popup to be visible as possible and the overflow to be handled gracefully.

Can you offer more details on the expectation? What does your Design specification say for this?

For the case where the Popup content does not fully fit in the viewport, would you expect it to stay on the part of the trigger with more room and:

1. be cut off suggesting the user to enlarge the size of the window?
**more likely to implement in Stardust**

2. shrink and display its content in a scrollable?
**less likely to implement in Stardust**

fyi @codepretty

**Comment by stuartlong** [comment]
Yup, that's exactly the issue.

Let me get more details on the expected design. But for now, I'd at least expect option 1, so that the user isn't totally confused why when they clicked on a button that no popup appeared.

**Comment by bmdalex** [comment]
### Short term fix - boolean prop to pin the content using `align` and `position` props

The short term fix will be to add a property that will turn off the auto positioning; we had requests where clients prefer to have the content positioned no matter if there is enough room in the viewport.

The prop could be called: `pinned`, `positionFixed` (conflicting with CSS props a bit)

e.g.
```jsx
<Popup align="start" position="above" pinned ... />
```

will create a `Popup` that will always be placed on top of the trigger aligned to the start (auto positioning will be turned off).

### Midterm - improve auto positioning and flipping algorithm

As a 2nd step, we will evaluate how difficult it'd be to improve the auto positioning and flipping algorithm in order to place the content on the part of the trigger with more room (for the case where the Popup content does not fully fit in the viewport).

For that we might need to contribute to `popper.js` (the library we're using for positioning items) and the whole process might take a while.

fyi @kuzhelov @layershifter

**Comment by bmdalex** [comment]
@stuartlong we believe we fixed this (at least short term) via #1471 but we'll keep the issue open for a while waiting for feedback from you and other users regarding a better fix; pls. let us know if you have any details on the expected design
