### ISSUE TITLE
Extra space occupied by Grid component

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1560]
## Bug Report
Grid component rendering with extra space
### Steps
I am using grid component for rendering share tray panels and the grid component is rendering with additional space as shown in the screenshot below. Can someone from Stardust team help me know how I can format it to avoid occupying the extra space.
This is how I am styling my Grid component.
{
gridTemplateColumns: "repeat(auto-fit, 14.8rem)",
gridTemplateRows: "repeat(auto-fit, 12.4rem)",
justifyContent: "start"
}
### Expected Result
![image](https://user-images.githubusercontent.com/47372422/60372177-91beb880-99b0-11e9-8132-d23b5b875158.png)
### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/47372422/60372133-6e940900-99b0-11e9-874d-e02a9a018f11.png)

###Code sandbox example:
https://codesandbox.io/s/grid-fit-items-pm63v
![image](https://user-images.githubusercontent.com/47372422/60855363-3a8ec400-a1b8-11e9-99a5-594d803d4286.png)

###TMP Code: 
https://domoreexp.visualstudio.com/Teamspace/_git/teams-modular-packages?path=%2Fpackages%2Fcomponents%2Fcomponents-calling-share-tray%2Fsrc%2Fcalling-share-tray.tsx&version=GBmaster

**Comment by kuzhelov** [comment]
`display: flex` style overrides shouldn't be used to customize Grid component. In the issue's example CSS grid props are mixed with grid layout, and this leads to unexpected rendering results. 

In general, style custoimizations should be avoided for layout components (`Grid`, `Flex`), especially customizations that are aimed to change layout aspects, as, in that case, it is component's responsibility to control them.

**Comment by vini-gupta** [comment]
This issue is not yet addressed even after removing display: flex 
This is what we are using now for styling the grid now: [source code](https://domoreexp.visualstudio.com/DefaultCollection/Teamspace/_git/teams-modular-packages?path=%2Fpackages%2Fcomponents%2Fcomponents-teams-stardust-ui%2Fsrc%2Fthemes%2Fteams%2Fcomponents%2FGrid%2Fgrid-styles.ts&version=GBmaster)
{
gridTemplateColumns: "repeat(auto-fit, 14.8rem)",
gridTemplateRows: "repeat(auto-fit, 12.4rem)",
justifyContent: "start"
}
https://teams.microsoft.com/l/message/19:add0d2b1c10f4b87b234a10fbfcdcd8b@thread.skype/1561688051181?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=adca7dff-4dd6-47f8-a4be-6eaadffadef4&parentMessageId=1561688051181&teamName=Teams%20Client%20NorthStar%20(N*)&channelName=Stardust&createdTime=1561688051181

@kuzhelov, @alinais, @hughreeling, @kumar-microsoft, @Bugaa92,  Please re-open this issue to track the grid layout fix for share tray.

**Comment by bmdalex** [comment]
@kuzhelov was right to close this issue for the reasons he mentioned

@vini-gupta this is an open source project that has a specific template for how issues are created.

Please refrain from pasting or mentioning code from your product because the level of detail discourages contributors to investigate.

Instead, try to create a clear and minimal [codesandbox](https://codesandbox.io) example where you're including **only** code that is relevant to the issue itself (leaving aside details related to your project).

Please try to encapsulate **what the issue is** and **what you're trying to achieve** by using our [**issues template**](https://github.com/stardust-ui/react/issues/new?template=Bug_report.md).
