### ISSUE TITLE
List, Toolbar, Menu: Item updates even when it is not necessary

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#1672]
### Steps
- Have a selectable `List` with items (A (selected), B, C)
- Select item B

### Expected Result
- item A is updated (as it is being deselected)
- item B is updated (as it is being selected)
- **item C is NOT updated (no change)**

### Actual Result
Item C is updated 💣

This is because of the `props` change.
For `ListItem` (not a complete list?):
- onFocus
- onClick

For `ToolbarItem`:
- icon
- menu
- onClick
- onMenuOpenChange
- variables

For `Menu`:
- onClick
- onActiveChanged
- variables

### Version
0.34.1

**Comment by layershifter** [comment]
This issue is based on a wrong assumption and actually, it was mine assumption 😿 I missed the key thing in React rendering.

----

https://reactjs.org/docs/optimizing-performance.html#avoid-reconciliation
https://reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action

By default React will render all children elements on the update root: 
![image](https://user-images.githubusercontent.com/14183168/63516125-aae57080-c4ec-11e9-8d90-4f7b574b611f.png)

I prepared a CodeSandbox to highlight it: https://codesandbox.io/s/heuristic-grothendieck-561kq. 

_On any update all items are rerendered._

***

Blocking rerenders is **not** recommended by React's team as the default plan 🥵
> However, there's deeper reasons why we're not sure we'd be adding it back. It contributes to the wrong idea that re-renders by themselves are bad (they're not if they're cheap). So people spend time optimizing useless things and missing actual performance issues.

https://github.com/facebook/react/issues/16437#issuecomment-522244087

---

However, React docs mentioned there is an way to avoid them via `shouldComponentUpdate()`, `PureComponent` or `React.memo()`. And second CodeSandbox shows it: https://codesandbox.io/s/smoosh-grass-7yue9.

Now, _only changed items were rerendered_.

---

_Does it mean that `React.memo()` solves performance issues?_ **Yes** and **no**.

**No**, for libraries. You can take a look on this discussion https://github.com/Semantic-Org/Semantic-UI-React/issues/1020#issuecomment-266922754, but the key things are below.

### ⚡ Checks are not cheap
`PureComponent`/`sCU`/`memo()` can slowdown your app because checks are not cheap and will be executed during each render.

### 💥 Props are always not equal
JSX `children` are always new objects. It's obvious in this CodeSandbox: https://codesandbox.io/s/relaxed-germain-gr40p

```jsx
<div>1</div> 
// https://reactjs.org/docs/react-without-jsx.html
// is equal to code below
React.createElement('div', null, 1) // => 
// { $$typeof: Symbol(react.element), type: "div", key: null, ref: null, props: {…}, …}
```

`React.createElement` returns always new object and these objects will be never equal.

```jsx
React.createElement('div', null, 1) === React.createElement('div', null, 1)
// false
```

It means that in 99% default check will be `false` and will cause a render, however _Checks are not cheap_. For Stardust it means that we can't use any tools to block updates 😱

So, when **yes**? On application level when you have enough knowledge about structure, performance issues and domain logic. Do we have a solution for `React.memo()` usage? **Yes**, it can be done via `render()` callback: https://codesandbox.io/s/silly-knuth-jukth

---

Is it bad to return new callbacks, _yeeess_. Should we invest the time solve it right now on library level? Probably, no.

**Comment by lucivpav** [comment]
> Do we have an escape plan for this goal? Yes, via render() callback: ...

Sorry I don't understand, what do you mean by an escape plan? Why not just use `memo()` on the application level, why do we need to call `render()`?

**Comment by layershifter** [comment]
> Sorry I don't understand, what do you mean by an escape plan? Why not just use `memo()` on the application level, why do we need to call `render()`?

Updated to:
> Do we have a solution for `React.memo()` usage?
