### ISSUE TITLE
[Dropdown] Selected values contain duplicates

### ISSUE THREAD

**Issue by kamilakorzec** [microsoft/fluent-ui-react#1786]
### Steps
1. Load dropdown with selected items:
![image](https://user-images.githubusercontent.com/11797698/62935776-475e9300-bdc8-11e9-80dd-6804877a3502.png)
2. Select the same item from the dropdown:
![image](https://user-images.githubusercontent.com/11797698/62935805-59403600-bdc8-11e9-9f58-8901413f4ef6.png)
3. For a split second the duplicated item appears as selected in the dropdown. When onSelectedChange is fired, the item appears twice in the value array:
![image](https://user-images.githubusercontent.com/11797698/62935873-8bea2e80-bdc8-11e9-84d7-d66c0ef06dfa.png)
4. Item disappears from the rendered dropdown
![image](https://user-images.githubusercontent.com/11797698/62935932-b20fce80-bdc8-11e9-9017-e8f93187d5e5.png)

### Expected Result
1. Selected items don't appear in the dropdown
2. Value cannot contain duplicated values

### Actual Result
1. I can select the same item twice
2. Selected item appears twice in the dropdown value when onSelectedChange is fired

### Version
0.34.4

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by lucivpav** [comment]
When one uses a `Dropdown` with `multiple` prop and selects an item, the same item cannot be chosen again as it disappears from the list. Can you provide a Codesandbox example?

**Comment by lucivpav** [comment]
The problem is with `lodash difference` if the arrays contain objects. Example: https://codesandbox.io/s/stardust-ui-example-wxx8q

**Comment by lucivpav** [comment]
After a fix is merged, you will want to use `Dropdown` with `itemToValue` prop, something like:
```
    itemToValue={(item) => {
      if (!item || !React.isValidElement(item)) {
        return ''
      }
      return item.key
    }}
```

**Comment by silviuaavram** [comment]
@lucivpav there is no issue with lodash difference. The issue is that you are creating two distinct objects in that example. 

https://codesandbox.io/s/stardust-ui-example-i8tr8

And in our docs we also have an example with objects [here](http://localhost:8080/components/dropdown/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#variations-search-multiple-image-and-content). Select items and there are no duplicates. Because the objects are just passed from `items` to `value` as references.

Maybe it's something wrong in how you are using it @kamilakorzec can you provide code sandbox?

**Comment by silviuaavram** [comment]
Ok, agree we can maybe provide a compare function as prop on the Dropdown.

We can close this issue once you change the implementation (remove duplicates) or if we are providing that prop and you will refactor the implementation to use it.

**Comment by lucivpav** [comment]
So I will add a new prop, called `compareBy` and it will be a function taking an `item` and returning `any`

**Comment by lucivpav** [comment]
https://github.com/stardust-ui/react/issues/1786#issuecomment-532209877
