### ISSUE TITLE
Simple way to use branding/primary colors on box component

### ISSUE THREAD

**Issue by hisuwh** [microsoft/fluent-ui-react#1829]
### Problem description
I want to be able to use the branding colors, specifically the primary option with my own components.  There might already be a way to do this, if so consider this a documentation request because I could not work out how to do it in a clean way.

I can style up a button like this:
```tsx
<Button primary />
```
But I cannot do this with a box, the closest I could come up with is this:
```tsx
<Box
    styles={theme => {
        return { backgroundColor: theme.theme.siteVariables.colors.brand[800] };
    }}
/>
```

### Proposed solution
Ideally I would like to see a primary prop on the Box component
```tsx
<Box primary />
```

Easier access to these things on the callback would be second choice:

```tsx
<Box
    styles={theme => {
        return { backgroundColor: theme.primary };
    }}
/>
```

Typings on siteVariables for colors, and a primary option on this would be last choice (I had to work this out by inspecting the output):

```tsx
<Box
    styles={theme => {
        return { backgroundColor: theme.theme.siteVariables.colors.primary };
    }}
/>
```

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

(not sure how a codepen can help here - also this codepen references semantic-ui-react...)

**Comment by levithomason** [comment]
## Consistency

A button has a `primary` prop because it is a UX idea, that there is a "primary" action to be invoked in some UI.

The color associated is a bit of a misnomer and something we may actually remove in favor of "accent" or similar.  There isn't a "primary" color palette in the same way that there is a "primary" action on a page.  It just so happens that the primary button on a page gets a certain color most of the time.

Because of this, we do not expose a "primary" prop on other components.

## `theme.primary`
`theme.primary` would have to make an assumption about which primary shade you wanted:

![image](https://user-images.githubusercontent.com/5067638/64387738-a68f7c00-cff1-11e9-8ace-28f2056efdfd.png)

For this reason, there cannot be a single `primary` color.

***

FWIW, we're pumped that you found the correct solution by digging 🎉  😸 

```jsx
<Box
    styles={theme => {
        return { backgroundColor: theme.theme.siteVariables.colors.brand[800] };
    }}
/>
```

**Comment by hisuwh** [comment]
Thanks for your response @levithomason and I totally get your design decisions here.  I had misunderstood the intention of primary so this now makes more sense.

Some documentation and better typings would be helpful here perhaps.  Maybe I will send pr if I can find the time (emphasis on maybe 😆).
