### ISSUE TITLE
Toolbar: overflow is not working in child window

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#1885]
### Steps
1. Open attached CodeSandbox
2. Click on `Open Window` button
3. Notice that `Toolbar` looks properly
4. Resize child window

### Expected Result
Resize occurred.

### Actual Result
Nothing happened.

![image](https://user-images.githubusercontent.com/14183168/64187923-b97b4280-ce71-11e9-9942-cc1513efb660.png)

### Version
0.37.0

### Testcase
https://codesandbox.io/s/stardust-ui-example-sqh81

**Comment by lucivpav** [comment]
The `window` reference is still pointing to the original window, rather than the new `externalWindow`

**Comment by lucivpav** [comment]
I could create an optional prop on `Toolbar` that would accept a window. But not sure if that's the right solution. Shouldn't `Provider` automatically handle the reference to the external document/window?

**Comment by miroslavstastny** [comment]
@lucivpav - let's say you pass `window` to `Toolbar` - what will you do with that there?
You can fix the `requestAnimationFrame` call but from what I and @levithomason debugged, the main problem is in native [`ResizeObserver`](https://drafts.csswg.org/resize-observer-1/) - there is no way how to pass custom document to it.

Because of that and reported performance issues with overflow, we will need to reconsider feature requirements and choose what to sacrifice.

**Comment by miroslavstastny** [comment]
Extended codesandbox: https://codesandbox.io/s/mw-resizeobserver-hkpgo

**Comment by layershifter** [comment]
It works if it's created on a proper `window`: https://codesandbox.io/s/mw-resizeobserver-r2zkd

However, there are no options for pofyfil 😭

**Comment by jurokapsiar** [comment]
closing this as it will be fixed in the new implementatioin of the automatic overflow.
