### ISSUE TITLE
Theme it and RTL buttons not work in the components documentation

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#1997]
### Steps
Open docs site page for a component
Click on Theme it
Click on RTL

### Expected Result
Theme panel is displayed
Example is displayed in RTL

### Actual Result
Theme panel is not displayed
Example is displayed in LTR

### Version
0.39.0

### Testcase
N/A

**Comment by miroslavstastny** [comment]
Broken theme it caused by #1957.
We no longer pass the whole `styleParam` to `renderRule`: https://github.com/stardust-ui/react/pull/1957/files#diff-2ac3e0121e5671c7bcbda123cd3c4b6aR218, but `useEnhancedRenderer` tries to read component name and variables from that.

Broken RTL (if source code is not displayed) is caused by #1940.
[Rendered example component](https://github.com/stardust-ui/react/pull/1940/files#diff-0b8ae45031726ce828bc94d3fea67a93R560) must be wrapped by `Provider` and `VariableResolver`.
