### ISSUE TITLE
Cannot pass variables to Input when using Form.Field

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#2143]
### Steps
In `Form.Field', the component can be customized using `control` shorthand prop, but in that case `variables` are not passed to the control.

### Expected Result
Variables provided in the control should be respected

### Actual Result
Variables are not applied

### Version
0.40.x

### Testcase
https://codesandbox.io/s/ecjq4?module=/example.js

**Comment by mnajdova** [comment]
The general problem here is that the Box component is used as a base component, and (maybe the wrong) suggestion of how to render different components was using the `as` property. The `Form.Field` component needs a bit of rethinking and will probably be updated in near future. In the meantime, here is a way of how to overcome this issue:

https://codesandbox.io/s/fluent-ui-example-sjj3e?fontsize=14&hidenavigation=1&theme=dark

The example in the codesandbox link should be enough for unblocking users, if you think that it is enough feel free to close the issue.. I will make sure to link this issue once we have PR that will do the necessary changes to the `Form.Field` component. I would not like to update the examples on the docs just now, because I am pretty sure there will be changes to the component soon.
