### ISSUE TITLE
Popup position example is not working properly in RTL mode

### ISSUE THREAD

**Issue by kuzhelov** [microsoft/fluent-ui-react#288]
When RTL mode is changed for `Popup` position example, popups are displayed improperly in the following sense:
- position of arrows on buttons should reflect RTL mode properly (while no changes are applied now)
- position for Popup is not switched (i.e. `start` and `end` values are not honoured)

![ezgif com-gif-maker 1](https://user-images.githubusercontent.com/4512430/46282562-20152380-c572-11e8-96e0-f13000b8a180.gif)

_Originally posted by @mnajdova in https://github.com/stardust-ui/react/pull/282#issuecomment-425854307_

**Comment by bmdalex** [comment]
@kuzhelov @mnajdova 
This actually works correctly; it just seems it doesn't because the grid used to display the buttons is completely mirrored in terms of CSS styles; to verify this just add different backgrounds for the 3 columns as in my DEMO below:

![cnsbef2zcj](https://user-images.githubusercontent.com/5442794/46288793-40031200-c587-11e8-9f35-3121c5b98235.gif)

So let's close this and (as @mnajdova suggested) make it obvious for the example that RTL works correctly

**Comment by kuzhelov** [comment]
@Bugaa92, thanks a lot for these insights! Maybe we should consider to apply some additional styles, just for the sake of making this fact more visible.. In either case, let me close this issue for now and see if we'll need to return to it - then we could consider additioanl styles tweaks to be introduced :)
