### ISSUE TITLE
Stardust font-based icons do not work 'create-react-app' project

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#339]
### Steps
Create CRA application using typescript scripts. Add @stardust/react as a dependency. Try to use some some font icon, for example ```<Icon name='calendar' />```

### Expected Result
The icon should be rendered

### Actual Result
This is rendered:
![image](https://user-images.githubusercontent.com/4512430/46655613-68ed5d80-cbac-11e8-91d7-11f6fe29264a.png)

### Version
0.9.0

**Comment by gopalgoel19** [comment]
We have the same problem in TMP as well. Do we need some additional setup to render icons?

**Comment by levithomason** [comment]
The issue here is that the Teams theme currently temporarily uses Font Awesome icons borrowed from Semantic UI.  However, it does not provide the CSS font face definition for the `Icons` font family which is required to render the Font Awesome icons.

The Semantic UI CSS _does_ include the font face definition, hence when the Teams theme is being loaded in a location that also loads Semantic CSS for icons, everything works.

The Teams theme will not use Font Awesome icons, but its own SVG icons only.  So, it doesn't make sense to add the font face definition right now.  If you'd like to use font awesome icons from Semantic UI in the Teams theme, you'll need to load the Semantic UI CSS for icons.

I'm closing this issue for now since it will not be fixed as we will not support Font Awesome icons in the Teams theme.  The actual bug is "Teams theme uses Font Awesome icons" :)
