### ISSUE TITLE
Rendering a Component outside of Provider should fail with meaningful error

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#372]
### Steps
Create a new application, create a component (`<Button />`) without wrapping that by `<Provider>`.

### Expected Result
Component rendering fails with meaningful error (or warning) 

### Actual Result
Component dom renders, no styles are applied 💣

### Version
0.9.1

**Comment by kuzhelov** [comment]
as an alternative to `Expected result`, we might consider to add support for default theme, so that the following elements tree, without being wrapped by Provider component, will be rendered with default styles applied:

```jsx
import { Button } from '@stardust-ui/react'

export const App = () => <Button />
```

Could we, please, mention the arguments against introducing default theme here, just to reconsider them. At the same time, agree that showing warning/error message is a good first step in either case.

**Comment by hughreeling** [comment]
What type of error is appropriate - console errors seems ok - but sometimes hard to find.  Message on screen very visible, but could be hugely annoying too...

**Comment by bmdalex** [comment]
@miroslavstastny @kuzhelov @hughreeling 
what about something like this?

![screen shot 2018-10-19 at 15 25 46](https://user-images.githubusercontent.com/5442794/47221071-ca36dd00-d3b3-11e8-893c-22bfcfde01d6.png)

created a PR for it, #378

**EDIT:.**
Unfortunately all tests will fail by doing it like this..
