### ISSUE TITLE
Performance downgrade (Fela)

### ISSUE THREAD

**Issue by kovhel** [microsoft/fluent-ui-react#404]
### Steps
Any re-render of stardust component e.g. List(List.Item)
No theme or styles are provided to list 

### Expected Result
Fela theme is not re-compiled on each render

### Actual Result
Theme update tooks significant time and causes downgrade in performance
Please see screenshot of Chrome dev tools/Performance/User Timing

![image](https://user-images.githubusercontent.com/18219717/47572850-38dbe380-d93c-11e8-83a6-752b6d9eb7be.png)

### Version
0.10.0

### Testcase
Please check sample that compares stardust list update vs simple HTML ul/li
https://codesandbox.io/s/42xmp69po0

**Comment by miroslavstastny** [comment]
We should definitely look into Stardust components' performance and we plan to do so.
To your codesandbox:
- development version of react is used so don't be scared by the absolute numbers,
- comparing the relative numbers, it is obvious that Stardust is slower than ul>li. But that's expected as Stardust does a lot more compared to plain ul>li. 
- The fact that the flame graph shows a lot of time spent in FelaTheme does not mean that fela took all that time. Each bar shows time taken by the operation itself (self time) **plus the time of all it's children**. As each Stardust component is wrapped by `FelaTheme` to consume a theme from a context, `FelaTheme` is always at the top level of the flame graph for each component (but ~always with self-time being 0).

**Comment by levithomason** [comment]
Thanks for the issue and keeping an eye.  There are a large number of perf optimizations available to us which will improve render times.  At the same time, Stardust will always take more time than plain HTML unless we remove runtime CSS in JS and theme merging.  Providing these features requires parsing and it is not free.  That said, I am confident that we will not have any performance issues given the number areas we can optimize.

I'm holding off on perf improvements until **1)** we get the perf tracking in place, see #141 **2)** we have a confirmed stable theme scheme and styling mechanism.  I want item 1 first so we know where to optimize and what our actual gains are.  I want item 2 so that we aren't optimizing things that we're going to remove or change entirely.

Let's make sure we get #141 over the finish line so we can iterate on this.

**Comment by kovhel** [comment]
Thank you for response! 
I just would like to mention that I haven't even provide any theme to the List and event handler does not touch any prop.

**Comment by levithomason** [comment]
We have added perf tracking and are collaborating with other libraries to further improve it.  We will continually monitor and improve perf as we go.

Any future comments should be directed to specific issues which we can open PRs against.  Thanks much!
