### ISSUE TITLE
Styles defined as functions in shorthand are not working

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#415]
### Steps
Define some styles as a function in any shorthand of the components. For example, in the Button, define the icon shorthand with some styles in form of a function.

```
<Button 
  type="primary" 
  icon={{
    name: "book", 
    styles: () => ({margin:'10px'}),
  }} 
  content="Click me before" 
  iconPosition="before" />
```

### Expected Result
The styles should be applied for the shorthand.

### Actual Result
They are not applied. The only way that those are applied is if the styles are defined as object 💣

### Version
0.11.0

**Comment by mnajdova** [comment]
We can overcome this by using the Provider immiditatelly before the component for defining the styles for the shorthand:
```
<Provider theme={{
            componentStyles: {
              Icon: {root: ({ theme }) => ({ ... some styles for the Icon...)},
            },
          }}
        >
          <Button icon='umbrella'/>
</Provider>
```

Not sure if we should move right into fixing this, as I guess it was implemented like this with a reason.

**Comment by levithomason** [comment]
The issue here is that `factories.tsx` are only merging styles objects.  They are not taking into account style functions.

### Short term (`good first issue`)
A partial fix would be to update `factories.tsx` to use `mergeComponentStyles()` opposed to `_.merge()`.  That would at least support both objects and functions.

### Long term
The factories might need to be able to render a component completely on their own.  This means they would need to be able to render the styles into classNames.  This would allow consumers to invoke the factories directly for their own components.

The consideration here is that the factory would need all the theme information (theme, renderer, variables) in order to convert styles to class names.  I'm not sure if this is appropriate or inappropriate for the factories to access.  It would mean factories are no longer about "creating an element" but they are about "rendering an element", which is a small but very important distinction.
