### ISSUE TITLE
Compile error on styles for correct CSS properties

### ISSUE THREAD

**Issue by vadimvar** [microsoft/fluent-ui-react#532]
### Steps
```jsx
styles = {
  shareFromSent_root: {
    marginTop: "10rem",
    paddingLeft: "3rem",
    paddingRight: "3rem",
    textAlign: "center",
    flexDirection: "column" as CSS.FlexDirectionProperty
  }
}
<Segment styles={styles.shareFromSent_root}>
```
### Expected Result
Expect styles are compiled
Have to use a workaround which looks weird but works fine
```jsx
<Segment styles={() => styles.shareFromSent_root}>
```

### Actual Result
```
TS2322: Type '{ marginTop: string; paddingLeft: string; paddingRight: string; textAlign: string; flexDirection: FlexDirectionProperty; }' is not assignable to type 'ComponentSlotStyle<SegmentProps, any>'.
  Type '{ marginTop: string; paddingLeft: string; paddingRight: string; textAlign: string; flexDirection: FlexDirectionProperty; }' is not assignable to type '(styleParam?: ComponentStyleFunctionParam<SegmentProps, any>) => ICSSInJSStyle'.
    Type '{ marginTop: string; paddingLeft: string; paddingRight: string; textAlign: string; flexDirection: FlexDirectionProperty; }' provides no match for the signature '(styleParam?: ComponentStyleFunctionParam<SegmentProps, any>): ICSSInJSStyle'.
Version: typescript 3.0.1
```
### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by vadimvar** [comment]
`<Segment styles={styles.shareFromSent_root}` doesn't work

**Comment by levithomason** [comment]
This issue template is not complete and I cannot tell what is being communicated.  Please complete the steps explicitly so that others can understand how to fix the issue.  Also, it is important to include the version number and update the test case.  We will then have the info we need to help, thanks!

**Comment by miroslavstastny** [comment]
The problem is that Typescript cannot correctly infer type for `shareFromSent_root`.
It infers `textAlign` to be a string but it should be TextAlignProperty (string literal). To avoid that kind of issues, you should type your objects explicitly, in this case `shareFromSent_root: ICSSInJSStyle`.

You should also avoid type assertions like `as CSS.FlexDirectionProperty` - these would allow you to pass in any invalid value without compiler complaining.
