### ISSUE TITLE
RTL works incorrectly when `rtl` theme prop is changed dynamically (with no remount of Provider)

### ISSUE THREAD

**Issue by kuzhelov** [microsoft/fluent-ui-react#581]
## Bug Report
Stardust component will be improperly displayed in RTL mode if `rtl` flag is changed dynamically for parent `Provider` component - i.e. when there is no remount of `Provider` component's instance happened. 

Specifically, the root cause of this issue is absence of remount for Fela's `Provider` component.

### Steps
- create simple example and render Stardust `Button` component
```jsx
import { Provider, Button } from '@stardust-ui/react'

// use any theme which has `rtl` being set to false by default
<Provider theme={teams}>
   <Button />
</Provider>
```
- open React Dev Tools, and for Stardust `Provider` component check `rtl` box to `true`

### Expected Result
- `rtl-*` classes should be generated in `<head> -> <style>` DOM element
- `rtl-*` should be applied to component's DOM node

### Actual Result
- 👍 `rtl-*` ARE applied to component's DOM node`
- 👎 but **there are no corresponding `rtl-*` classes generated for `<head> -> <style>` DOM element of the page** - thus, styles of these classes are not applied to component

### Version
0.14.0

**Comment by layershifter** [comment]
This happens because `RendererProvider` calls [`render()`](https://github.com/rofrischmann/fela/blob/master/packages/fela-dom/src/dom/render.js#L8)  only in its [`constructor()`](https://github.com/rofrischmann/fela/blob/master/packages/fela-bindings/src/RendererProviderFactory.js#L34) and this means that a subscription for DOM updates will be never created.

I found the similar issue, https://github.com/rofrischmann/fela/issues/388 and it seems that renderer replacement is not possible by the design 🤔 However, I have a strong opinion that we should fix this at least on our side.
