### ISSUE TITLE
Provider is not setting styles to theme

### ISSUE THREAD

**Issue by hughreeling** [microsoft/fluent-ui-react#586]
### Steps
Create react-app and add Stardust

```jsx
 // index.js

import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import \* as serviceWorker from './serviceWorker';
import { Provider, themes } from '@stardust-ui/react'

ReactDOM.render(
   <Provider theme={themes.teams}>
    <App />
  </Provider>,
   document.getElementById('root')
);
```

```jsx
// App.js

import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Text, Provider, themes, Button } from '@stardust-ui/react'

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
           <Text content="Learn React" />
           <Provider theme={ themes.teamsDark }> { /* <-------- !!! */ }
               <Text content="Build your future" />
           </Provider>
        </header>
      </div>
    );
  }
}

export default App;
```
![image](https://user-images.githubusercontent.com/6866507/49738518-db071f00-fc8f-11e8-8df2-37e4c9db4739.png)

### Expected Result
"Learn React" would be black text on white background - like teams theme
"Build your Future" would be white text on black background - as dark theme

### Actual Result
The actual result that happened 💣

Theme styles are not visually applied at all.  Currently would need to wrap in segment, or apply manually from styling variables.

### Version
0.14.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

### Suggestion
The Provider should generate div and apply the theme related styles.  Theme could select which inherited styles they apply (colours, fonts, etc)

**Comment by miroslavstastny** [comment]
## Problem description

There are two problems here:
### colors are not applied
```jsx
<Provider theme={{teamsDark}}>
  <Text>text in Stardust component</Text>
  <p>text inside html element</p>
</Provider>
```
Consumer expectations are that both texts should be light on dark background. `Text` component should not set colors, it should inherit them.

### dir="rtl" is not applied
```jsx
<Provider theme={{rtl: true, ...}}>
  <Component1/>
  <Component2/>
</Provider>
```
As components are wrapped by RTL provider, they should be displayed from right to left.

## Proposed solution

- change `Provider` to be `UIComponent`,
- add styles to set `color` and `background-color` accordingly,
- render `Provider` as `<div dir="rtl" />` for RTL and `<div dir="ltr" />` for LTR (this is required in order to be able to nest LTR provider inside a RTL one).
