### ISSUE TITLE
Problems with Input component

### ISSUE THREAD

**Issue by johannao76** [microsoft/fluent-ui-react#754]
I am trying to use Input to render a textarea. I am able to get it to render with the correct styling. However, I am unable to prepopulate with a value that the user can then edit. I tried setting both the value prop and the defaultValue prop. Setting value populates the value initially, but when the user types characters in the field, nothing happens. I debugged this a bit and in this case, the text is updated and there is a state change but the re-render cycle uses the old text. Setting the defaultValue prop causes the text to not render at all in the text area. Snippets of each approach:
```tsx
<Input
  input={{
    as: "textarea",
    rows: "4",
    maxLength: 150,
    value: captionText,
    styles: styles.editorTextArea
  }}
/>
```
```tsx
<Input
    input={{
    as: "textarea",
    rows: "4",
    maxLength: 150,
    defaultValue: captionText,
    styles: styles.editorTextArea
  }}
/>
```
I also tried with Input as a normal textbox and here defautlValue works but value does not.
```tsx 
// Works
<Input styles={styles.editorTextBox} defaultValue={placeholderText} />

// Does not work
<Input styles={styles.editorTextBox} value={placeholderText} />
```
Edit: Confirmed that for the textarea example, when we create the slot component, the props passed in include the old value. Could trace this back to the following code in Input.renderComponent, here when the input prop is passed in, it is passed as-is to Slot, and this contains the old value.
```tsx
} }, Slot.create(input || type, {
```

**Comment by levithomason** [comment]
### Fix

We need to provide a `<TextArea />` component.

### Workaround
This can be done the way you are trying to do it but it is a little tricky.

The `Input` manages it's own state, but only according to the `Input`'s props.  You'll need to pass `defaultValue` as a top-level prop, instead of a props key in the `input={}` shorthand:

```jsx
  <Input
    defaultValue="captionText"
    input={{
      as: 'textarea',
      rows: 4,
      maxLength: 150,
    }}
  />
```

I think this makes sense, because, the Input doesn't know anything about the props for the `textarea` child you are defining.  Therefore, it won't use them properly.  A counter case might be made, but this is a workaround for now while we wait on a `<TextArea />`.

**Comment by levithomason** [comment]
Note, the reason it "does not work" with a `value` prop is because that is a controlled component.  You'd need to handle state updates yourself:

https://reactjs.org/docs/forms.html#controlled-components

**Comment by levithomason** [comment]
See #755 for the component request.
