### ISSUE TITLE
TruncateEnd property in Layout component is not truncating content with ellipsis.

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#849]
### Steps
The truncateEnd property in Layout component is just truncating the text without showing ellipsis.

### Expected Result
The result that you expected.
![image](https://user-images.githubusercontent.com/47372422/52313662-2b36f080-2964-11e9-814d-a990562a61e8.png)

### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/47372422/52313644-10fd1280-2964-11e9-9b2d-2c27223fbf3a.png)

### MitigationSteps
The truncateEnd property should have display:"block" instead of "flex" to truncate with ellipsis.

[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y
![image](https://user-images.githubusercontent.com/47372422/52313617-f4f97100-2963-11e9-8e71-b7c9bbe9a9e0.png)
![image](https://user-images.githubusercontent.com/47372422/52313789-ba440880-2964-11e9-889b-2da926189398.png)

**Comment by bmdalex** [comment]
@vini-gupta - thanks for reporting this, it's something we should fix. 

Here are some attempts and after that our resolution and solution.

### Attempt no. 1: `display: 'block'` instead of `display: 'flex'` (proposed by @vini-gupta )

Using `display: 'block'` instead of `display: 'flex'` (or `display: 'grid'` for the main area) won't work for us because it'll break alignment of the items inside the `start`, `main` and `end` areas.

See: **https://codesandbox.io/s/1rm85vyyl7**
![Screenshot 2019-03-28 at 21 20 52](https://user-images.githubusercontent.com/5442794/55190411-0ad72580-51a0-11e9-8f4a-3c61201f8dae.png)

### Attempt no. 2: Wrap `ReactText` (strings or numbers) in a span to achieve the ellipsis

Following https://css-tricks.com/flexbox-truncated-text/ article we could detect if the user passes string | number primitives to `start`, `main` and `end` areas and wrap them with a span.

However, we cannot do that because it'd imply that `Layout` component will have opinions on the elements we pass and the structure of the rendered DOM will change based on that. This contradicts Stardust principles.

### Resolution

Since `truncate*` props (`truncateStart`, `truncateMain`, `truncateEnd`) failed to handle all truncation cases we decided to remove them from the API. We will do the same for `ItemLayout`. (BREAKING CHANGE)

### Solution

Wrap the element that you need truncated with `truncated` `Text` component and pass that element to `Layout`'s `end` slot

```jsx
<Layout
  // ...
  end={<Text truncated>My long text that I need truncated</Text>}
  endCSS={{ overflow: 'hidden' }}
/>
```
See complete code: **https://codesandbox.io/s/pm4vn7j0mm**

fyi @kuzhelov @mnajdova
