### ISSUE TITLE
Acc - Reader - "VoiceOver keys" - VoiceOver narrate wrongly position in menu

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluent-ui-react#982]
### Steps
Navigate to the menu component:
https://stardust-ui.github.io/react/components/menu
OSX/Chrome/VoiceOver
Navigate through the each menu on the page using VoiceOver keys. (Control+Option+right/left arrow key)

### Expected Result
position in the menu is narrated correctly as  
1 of [total number of menu items]
2 of [total number of menu items]
3  of [total number of menu items]
etc...

### Actual Result
VoiceOver narrate position incorrectly on some menus, like:
2 of 6
4 of 6
6 of 6
even menu has only 3 menu items.

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by miroslavstastny** [comment]
Menu uses `:before` for vertical line between items.
It can be probably fixed by `boxShadow`:
```jsx
boxShadow: `-1px 0 0 0 ${primary ? v.primaryBorderColor : v.borderColor} inset`
```

But `pointing` menu uses `:after` for the beak:
![image](https://user-images.githubusercontent.com/9615899/54525700-18590800-4975-11e9-9f80-911ba77f95ae.png)
I have no idea how this could be avoided. But even with this, getting rid of the `:before` would improve the current situation.

Other than that, there are almost 10 other places in Teams theme where `:before` or `:after` is used.  Are we sure screen readers are happy with all other ones?

**Comment by miroslavstastny** [comment]
#1066 does not fix OSX/Chrome/VoiceOver.
