### ISSUE TITLE
pxToRem sometimes returning incorrect size

### ISSUE THREAD

**Issue by bcalvery** [microsoft/fluent-ui-react#988]
pxToRem is sometimes outputting incorrect values. It appears to sometimes use the wrong remSize in its calculations.

Observed:
![image](https://user-images.githubusercontent.com/15043460/53529471-8ced0500-3aa1-11e9-90b2-998ab453729e.png)

Expected:
![image](https://user-images.githubusercontent.com/15043460/53529624-0be23d80-3aa2-11e9-8e2c-688387d7721f.png)
The results are consistent with using 16px as the HTML font-size, but in most cases the correct value of 14px is used.

**Comment by kuzhelov** [comment]
acknowledging the problem - root cause is the fact that `siteVariables` are calculated before theme has provided any static styles, and, thus, before theme's html font size was applied - thus, for `pxToRem` calculations default 16px is used.

Currently see two options for us to address this issue:
- remove static styles support from Stardust themes. In that case we might expect no changes to html font size being brought by loaded theme, so the problem will disappear. As an additional benefit, we will eliminate any possibility for global styles being leaked from loaded theme  and affecting the _entire_ app's page
- use lazy evaluation mechanism for some of the variables, something like the following one, in case of font sizes - and remove `pxToRem` from direct exports in Stardust:

```js
export const fontSizes = ({ pxToRem }) => ({
  smaller: pxToRem(10),
  ..
  larger: pxToRem(24)
})
```

Both options imply deign changes, but I would rather vote for the first one, as it would result in generally simpler approach, with site variables remaining to be just plain objects. Please, folks, let me know about your thoughts on that.

Cc: @mnajdova, @miroslavstastny, @layershifter, @alinais, @Bugaa92, @levithomason

**Comment by layershifter** [comment]
> remove static styles support from Stardust themes.

Personally I vote for this, this will allow to get rid of this #960. But we will still need `staticStyles` like `normalize.css`.

Can we introduce a separate provider for them? `StaticProvider`? It will be not super-friendly, but will clarify the responsibilities.

**Comment by levithomason** [comment]
We can't remove the static styles without consequence.  It would mean HTML font size wouldn't be set, normalize.css wouldn't be applied, and global styles such as font-family, box-sizing, body color, etc could not be set.

There is a third option, which I believe is the correct one, the `pxToRem` utility should get its html font-size value from the theme, where it is defined, not from querying the browser.
